### ISSUE TITLE
Config.json

### ISSUE THREAD

**Issue by NekWasTaken** [StandB/whatanime-discord#2]
What is the difference between the **wa_token** and the **d_token**

**Comment by StandB** [comment]
wa_token refers to a trace.moe (previously named whatanime) token to use their API for anime recognition.
d_token is the discord token necessary to run the bot itself.

**Comment by NekWasTaken** [comment]
Where would I be able to find the API token?

**Comment by StandB** [comment]
probably by contacting [soruly](https://github.com/soruly), the dev of trace.moe. I requested one years ago, not sure if he still sends out API tokens.

**Comment by StandB** [comment]
soruly has updated the API and removed the need for a token. I have updated this project accordingly, so now only a discord token is needed.
